@startuml Registrar equipo desde un excel
skinparam Style strictuml
skinparam SequenceMessageAlignment center

boundary Usuario
control RESTServiceGIV
entity Response
entity CEquipos
participant BLEquipos
entity Equipos
participant Equipos as ListEquipos <<ObservableCollection>>
participant TransactionScope
participant Util

Usuario -> RESTServiceGIV: AddEquipos(request: RequestRestGIV): Response
activate RESTServiceGIV
create Response
RESTServiceGIV -->> Response: Response()
RESTServiceGIV -> RESTServiceGIV: ValidarSession(token: Guid, x_itemRequest: Request, ref x_tiempo: int): Boolean
alt Sesión Válida
    create BLEquipos
    RESTServiceGIV -->> BLEquipos: BLEquipos()
    create ListEquipos
    RESTServiceGIV -->> ListEquipos: ObservableCollection<Equipos>()
    loop CEquipos
        create Equipos
        RESTServiceGIV -->> Equipos: Equipos()
        RESTServiceGIV -> CEquipos: CopyTo(ref Item: Equipos): void
        activate CEquipos
        deactivate CEquipos
        RESTServiceGIV -> ListEquipos: Add(item: Equipos): void
        activate ListEquipos
        deactivate ListEquipos
    end
    RESTServiceGIV -> BLEquipos: Save(ref Items: ObservableCollection<Equipos>): Boolean
    activate BLEquipos
    create TransactionScope
    BLEquipos -->> TransactionScope: TransactionScope()
    alt InstanceEntity.Added
        BLEquipos -> BLEquipos: InsertJSON(ref Item: ObservableCollection<Equipos>): bool
    else InstanceEntity.Modified
        BLEquipos -> BLEquipos: UpdateJSON(ref Item: ObservableCollection<Equipos>): bool
    end
    alt Guardado exitoso
        BLEquipos -> TransactionScope: Complete()
        activate TransactionScope
        deactivate TransactionScope
    end
    BLEquipos -->> RESTServiceGIV: bool
    alt Exception
        BLEquipos -->> RESTServiceGIV: throw
    end
    deactivate BLEquipos
    alt bool = true
        Response -> Response: Codigo = 0
        activate Response
        deactivate Response
        Response -> Response: Mensase = "Se realizó correctamente el registro de los equipos."
        activate Response
        deactivate Response
    else
        Response -> Response: Codigo = 1
        activate Response
        deactivate Response
        Response -> Response: Mensase = "Ha ocurido un error al realizar el registro de los equipos. </br>"
        activate Response
        deactivate Response
    end
    Response -> Response: TiempoSesion = _tiempodisponible
    activate Response
    deactivate Response
else
    Response -> Response: Codigo = 98
    activate Response
    deactivate Response
    Response -> Response: Mensase = string.Format("Mensaje: {0} - Tiempo Disponible: {1} minutos", "TOKEN No Valido", _tiempodisponible)
    activate Response
    deactivate Response
end
alt Exception
    Response -> Response: Codigo = 1
    activate Response
    deactivate Response
    Response -> Response: Mensase = string.Format("Error-{0}: {1}", _code, ex.Message)
    activate Response
    deactivate Response
    RESTServiceGIV -> Util: WriteError(x_CodeError: String, ex: Exception, x_Metodo: String, x_ParAdic: String, x_JSON: String): String
    activate Util
    deactivate Util
end
RESTServiceGIV -->> Usuario: Response
@enduml