import { RouteInfo } from "./sidebar.metadata";
export const ROUTES: RouteInfo[] = [
    {
        path: "/dashboard",
        title: "Inicio",
        iconType: "material-icons-two-tone",
        icon: "space_dashboard",
        class: "",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["All"],
        submenu: [],
    },
    {
        path: "",
        title: "Conquistadores",
        iconType: "material-icons-two-tone",
        icon: "face",
        class: "menu-toggle",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["Director"],
        submenu: [
            {
                path: "/conquistador/registro",
                title: "Registrar",
                iconType: "",
                icon: "",
                class: "ml-menu",
                groupTitle: false,
                badge: "",
                badgeClass: "",
                role: ["Director"],
                submenu: [],
            },
            {
                path: "/conquistador/roles",
                title: "Asignar roles",
                iconType: "",
                icon: "",
                class: "ml-menu",
                groupTitle: false,
                badge: "",
                badgeClass: "",
                role: ["Director"],
                submenu: [],
            },
            {
                path: "/conquistador/inscribir",
                title: "Inscribir",
                iconType: "",
                icon: "",
                class: "ml-menu",
                groupTitle: false,
                badge: "",
                badgeClass: "",
                role: ["Director"],
                submenu: [],
            },
        ],
    },
    {
        path: "",
        title: "Padres",
        iconType: "material-icons-two-tone",
        icon: "face",
        class: "menu-toggle",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["Director"],
        submenu: [
            {
                path: "/tutor/registro",
                title: "Registrar",
                iconType: "",
                icon: "",
                class: "ml-menu",
                groupTitle: false,
                badge: "",
                badgeClass: "",
                role: ["Director"],
                submenu: [],
            },
        ],
    },
    {
        path: "",
        title: "Actividades",
        iconType: "material-icons-two-tone",
        icon: "space_dashboard",
        class: "menu-toggle",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["Director"],
        submenu: [
            {
                path: "/actividad/crear",
                title: "Crear",
                iconType: "",
                icon: "",
                class: "ml-menu",
                groupTitle: false,
                badge: "",
                badgeClass: "",
                role: ["Director"],
                submenu: [],
            },
            {
                path: "/actividad/asistentes",
                title: "Registrar asistentes",
                iconType: "",
                icon: "",
                class: "ml-menu",
                groupTitle: false,
                badge: "",
                badgeClass: "",
                role: ["Director"],
                submenu: [],
            },
        ],
    },
    {
        path: "",
        title: "Multi level Menu",
        iconType: "material-icons-two-tone",
        icon: "slideshow",
        class: "menu-toggle",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["Admin"],
        submenu: [
            {
                path: "/multilevel/first1",
                title: "First",
                iconType: "",
                icon: "",
                class: "ml-menu",
                groupTitle: false,
                badge: "",
                badgeClass: "",
                role: [""],
                submenu: [],
            },
            {
                path: "/",
                title: "Second",
                iconType: "",
                icon: "",
                class: "ml-sub-menu",
                groupTitle: false,
                badge: "",
                badgeClass: "",
                role: [""],
                submenu: [
                    {
                        path: "/multilevel/secondlevel/second1",
                        title: "Second 1",
                        iconType: "",
                        icon: "",
                        class: "ml-menu2",
                        groupTitle: false,
                        badge: "",
                        badgeClass: "",
                        role: [""],
                        submenu: [],
                    },
                    {
                        path: "/",
                        title: "Second 2",
                        iconType: "",
                        icon: "",
                        class: "ml-sub-menu2",
                        groupTitle: false,
                        badge: "",
                        badgeClass: "",
                        role: [""],
                        submenu: [
                            {
                                path: "/multilevel/thirdlevel/third1",
                                title: "third 1",
                                iconType: "",
                                icon: "",
                                class: "ml-menu3",
                                groupTitle: false,
                                badge: "",
                                badgeClass: "",
                                role: [""],
                                submenu: [],
                            },
                        ],
                    },
                ],
            },
            {
                path: "/multilevel/first3",
                title: "Third",
                iconType: "",
                icon: "",
                class: "ml-menu",
                groupTitle: false,
                badge: "",
                badgeClass: "",
                role: [""],
                submenu: [],
            },
        ],
    },
];
