import { RouteInfo } from "./sidebar.metadata";
export const ROUTES: RouteInfo[] = [
    {
        path: "",
        title: "BIENVENIDO",
        iconType: "",
        icon: "",
        class: "",
        groupTitle: true,
        badge: "",
        badgeClass: "",
        role: ["All"],
        submenu: [],
    },

    {
        path: "/dashboard",
        title: "Inicio",
        iconType: "material-icons-two-tone",
        icon: "space_dashboard",
        class: "",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["All"],
        submenu: [],
    },

    {
        path: "/dashboard",
        title: "Administrador",
        iconType: "material-icons-two-tone",
        icon: "space_dashboard",
        class: "",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["Administrador"],
        submenu: [],
    },

    {
        path: "/dashboard",
        title: "Director",
        iconType: "material-icons-two-tone",
        icon: "space_dashboard",
        class: "",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["Director"],
        submenu: [],
    },

    {
        path: "/dashboard",
        title: "Consejero",
        iconType: "material-icons-two-tone",
        icon: "space_dashboard",
        class: "",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["Consejero"],
        submenu: [],
    },

    // Admin Modules
    {
        path: "",
        title: "MENUITEMS.DASHBOARD.TEXT",
        iconType: "material-icons-two-tone",
        icon: "space_dashboard",
        class: "menu-toggle",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["Admin"],
        submenu: [
            {
                path: "/admin/dashboard/main",
                title: "MENUITEMS.DASHBOARD.LIST.DASHBOARD1",
                iconType: "",
                icon: "",
                class: "ml-menu",
                groupTitle: false,
                badge: "",
                badgeClass: "",
                role: [""],
                submenu: [],
            },
            {
                path: "/admin/dashboard/dashboard2",
                title: "MENUITEMS.DASHBOARD.LIST.DASHBOARD2",
                iconType: "",
                icon: "",
                class: "ml-menu",
                groupTitle: false,
                badge: "",
                badgeClass: "",
                role: [""],
                submenu: [],
            },
        ],
    },
    {
        path: "/patient/dashboard",
        title: "MENUITEMS.DASHBOARD.LIST.PATIENT-DASHBOARD",
        iconType: "material-icons-two-tone",
        icon: "space_dashboard",
        class: "",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["Patient"],
        submenu: [],
    },
    {
        path: "",
        title: "Multi level Menu",
        iconType: "material-icons-two-tone",
        icon: "slideshow",
        class: "menu-toggle",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["Admin"],
        submenu: [
            {
                path: "/multilevel/first1",
                title: "First",
                iconType: "",
                icon: "",
                class: "ml-menu",
                groupTitle: false,
                badge: "",
                badgeClass: "",
                role: [""],
                submenu: [],
            },
            {
                path: "/",
                title: "Second",
                iconType: "",
                icon: "",
                class: "ml-sub-menu",
                groupTitle: false,
                badge: "",
                badgeClass: "",
                role: [""],
                submenu: [
                    {
                        path: "/multilevel/secondlevel/second1",
                        title: "Second 1",
                        iconType: "",
                        icon: "",
                        class: "ml-menu2",
                        groupTitle: false,
                        badge: "",
                        badgeClass: "",
                        role: [""],
                        submenu: [],
                    },
                    {
                        path: "/",
                        title: "Second 2",
                        iconType: "",
                        icon: "",
                        class: "ml-sub-menu2",
                        groupTitle: false,
                        badge: "",
                        badgeClass: "",
                        role: [""],
                        submenu: [
                            {
                                path: "/multilevel/thirdlevel/third1",
                                title: "third 1",
                                iconType: "",
                                icon: "",
                                class: "ml-menu3",
                                groupTitle: false,
                                badge: "",
                                badgeClass: "",
                                role: [""],
                                submenu: [],
                            },
                        ],
                    },
                ],
            },
            {
                path: "/multilevel/first3",
                title: "Third",
                iconType: "",
                icon: "",
                class: "ml-menu",
                groupTitle: false,
                badge: "",
                badgeClass: "",
                role: [""],
                submenu: [],
            },
        ],
    },
];
